name: 'Link Checker Action'
description: 'Checks the integrity of links in the PR'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  prNumber:
    description: 'Pull Request Number'
    required: true
outputs:
  pr-summary:
    description: 'Summary CSV for problematic links'
  baseline-unresolved:
    description: 'Baseline unresolved links CSV'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Extract PR Number & Set Preview URL
      run: |
        echo "PREVIEW_URL=deploy-preview-${{ inputs.prNumber }}--fluxcd.netlify.app" >> $GITHUB_ENV
      shell: bash

    - name: Run main target
      run: make main
      shell: bash

    - name: Clean cache
      run: make clean-cache
      shell: bash

    - name: Run with preview
      run: make run_with_preview
      shell: bash

    - name: Normalize reports
      run: make normalize
      shell: bash

    - name: Run summary
      run: make summary
      continue-on-error: true
      shell: bash

    - name: Check summary results
      run: ./.github/scripts/check_summary.sh
      shell: bash

    - name: Comment on PR if necessary
      run: ./.github/scripts/comment_on_pr.sh
      shell: bash
