name: Docker Image CI

on:
  push:
    branches: [ v1-beta ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/kingdonb/link-checker-gpt:v1-beta
          cache-from: type=gha
          cache-to: type=gha,mode=max
